processes:
  api:
    depends_on:
      docker:
        condition: process_healthy
    command: "just dev-api"
  web:
    command: "just dev-web"
  docker:
    command: "just docker-up"
    readiness_probe:
      exec:
        command: "pg_isready -h localhost -p 5432"
      initial_delay_seconds: 5 
      period_seconds: 3
    shutdown:
      command: "just docker-down"
